version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.13
    working_directory: ~/project

    steps:
      - checkout

      # -------------------------
      # Install Docker
      # -------------------------
      - setup_remote_docker

      # -------------------------
      # Backend
      # -------------------------
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Django System Check
          command: |
            cd backend
            python manage.py check

      # -------------------------
      # Install Node.js
      # -------------------------
      - run:
          name: Install Node.js
          command: |
            export NVM_DIR="$HOME/.nvm"
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            . "$NVM_DIR/nvm.sh"
            nvm install 22
            nvm use 22
            node --version
            npm --version

      # -------------------------
      # Frontend
      # -------------------------
      - run:
          name: Install Frontend Dependencies
          command: |
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"
            cd frontend
            npm install

      - run:
          name: Build React Application
          command: |
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"
            cd frontend
            npm run build

      # -------------------------
      # Docker
      # -------------------------
      - run:
          name: Build Backend Docker Image
          command: |
            docker build -t tasksphere-backend ./backend

      - run:
          name: Build Frontend Docker Image
          command: |
            docker build -t tasksphere-frontend ./frontend

workflows:
  version: 2
  build:
    jobs:
      - build