version: 2.1

jobs:

  backend:
    docker:
      - image: cimg/python:3.13

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Django System Check
          command: |
            cd backend
            python manage.py check

      - run:
          name: Run Django Tests
          command: |
            cd backend
            python manage.py test

  frontend:
    docker:
      - image: cimg/node:22.11

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install

      - run:
          name: Build React Application
          command: |
            cd frontend
            npm run build

workflows:
  version: 2

  build:
    jobs:
      - backend
      - frontend