version: 2.1

jobs:

  backend:
    docker:
      - image: cimg/python:3.13

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - backend-v1-{{ checksum "backend/requirements.txt" }}

      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          key: backend-v1-{{ checksum "backend/requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Django System Check
          command: |
            cd backend
            python manage.py check

      - run:
          name: Run Django Tests
          command: |
            cd backend
            python manage.py test

  frontend:
    docker:
      - image: cimg/node:20.18

    working_directory: ~/project

    steps:
      - checkout

      - restore_cache:
          keys:
            - frontend-v1-{{ checksum "frontend/package-lock.json" }}

      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm ci

      - save_cache:
          key: frontend-v1-{{ checksum "frontend/package-lock.json" }}
          paths:
            - frontend/node_modules

      - run:
          name: Build React Application
          command: |
            cd frontend
            npm run build

workflows:
  version: 2

  build:
    jobs:
      - backend
      - frontend